name: CommandPay
main: me.dirnei.commandpay.CommandPay
version: 0.4.1
author: Dirnei
description: Payment for Commands
commands:
  cp:
    description: Does nothing yet
    usage: |
        cp set [command] <price> - dont work